@VerticalSliceDemo_HostAddress = http://localhost:5170

GET {{VerticalSliceDemo_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{VerticalSliceDemo_HostAddress}}/api/product/getAll
Accept: application/json

###